# Generated by Django 4.0.4 on 2022-07-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryModels',
            new_name='Delivery',
        ),
    ]
