# Generated by Django 4.0.4 on 2022-07-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='date_added',
        ),
        migrations.AddField(
            model_name='delivery',
            name='phone_number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pickup_location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
