# Generated by Django 4.0.4 on 2022-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_remove_delivery_date_added_delivery_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
