# Generated by Django 4.0.4 on 2022-08-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0008_delivery_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_items',
            field=models.ManyToManyField(null=True, to='storeapp.orderitem'),
        ),
    ]
