# Generated by Django 4.0.4 on 2022-08-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0009_delivery_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='order_items',
        ),
    ]
