# Generated by Django 4.0.4 on 2022-09-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0012_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
