# Generated by Django 4.0.4 on 2022-09-26 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0013_delivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-transaction_id']},
        ),
    ]
