# Generated by Django 4.0.4 on 2022-10-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0014_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_brifing',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
